import type { Metadata } from "next";
import {Rajdhani } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS
import { config } from '@fortawesome/fontawesome-svg-core';
import LayoutClient from "./LayoutClient";
import { MAINTENANCE_MODE } from "../lib/constants";
config.autoAddCss = false; // Prevent Font Awesome from auto-injecting CSS

export const metadata: Metadata = {
  title: "KS Agrotech",
  description: "Generated by create next app",
};

const rajdhani = Rajdhani({
  subsets:["latin"],
  variable: "--font-rajdhani",
  weight: ['400', '500', '600', '700'], // Include only the weights you need
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${MAINTENANCE_MODE ? "maintenance-mode" : ""}`;
 return (
    <html lang="en" className={`${rajdhani.variable} ${bodyClassName}`}>
      <body className={`rajdhani-font antialiased bgColor ${bodyClassName}`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
