import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS
import { config } from '@fortawesome/fontawesome-svg-core';
import LayoutClient from "./LayoutClient";
import { MAINTENANCE_MODE } from "../lib/constants";
config.autoAddCss = false; // Prevent Font Awesome from auto-injecting CSS

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KS Agrotech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${MAINTENANCE_MODE ? "maintenance-mode" : ""}`;
 return (
    <html lang="en" className={`${bodyClassName}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${bodyClassName}`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
